### ISSUE TITLE
Docker Hub image needs to be rebuilt

### ISSUE THREAD

**Issue by hlapp** [rocker-org/ropensci#2]
There are a number of CI tests (including, for example, the Circle CI tests for [rOpenSci/RNeXML](https://github.com/ropensci/RNeXML)) that use the [rocker/ropensci Docker image](https://hub.docker.com/r/rocker/ropensci/). During the last few days some CRAN packages have updated with changes that aren't backwards compatible, making those tests fail ([example](https://circleci.com/gh/ropensci/RNeXML)). Could you trigger a rebuild of the image?

**Comment by cboettig** [comment]
Yup thanks.  Actually looks like the dependency `hadleyverse` image needs to be rebuilt to pick up the new `dplyr`.  It will then automatically cause `ropensci` to rebuild and should fix our circle issues.
