### ISSUE TITLE
Is This Image Being Maintained?

### ISSUE THREAD

**Issue by NarekA** [rocker-org/ropensci#8]
Hello, I wanted to use this image as the base image for my project, but it looks as though it is not being actively maintained. Are there any plans to update the builds in the registry?

**Comment by cboettig** [comment]
Good point, I'll tickle the builds and see where we are at.  This isn't intended as a general-purpose base image, `rocker/geospatial` is probably the right choice for that, and most ropensci packages can be installed on top of that image without much effort.  There's not much of a use case for having all rOpenSci packages pre-installed, beyond our internal use in testing the suite, so we should probably consider moving this over to the ropensci side.
